// Mock users with different roles
export const mockUsers = {
  admin: {
    avatars: [],
    id: '98cea92c-84e5-4c0d-ac21-9998f4b23883',
    firstName: 'Admin',
    authenticationUid: null,
    avatar: null,
    createdAt: '2020-05-12T11:04:00.864Z',
    createdById: null,
    deletedAt: null,
    disabled: false,
    email: 'admin@healthcare.com',
    emailVerificationToken: null,
    emailVerificationTokenExpiresAt: null,
    emailVerified: true,
    importHash: null,
    lastName: 'User',
    password: 'admin123',
    passwordResetToken: null,
    passwordResetTokenExpiresAt: null,
    phoneNumber: '+1-555-0101',
    provider: 'local',
    role: 'admin',
    updatedAt: '2020-05-12T11:04:00.864Z',
    updatedById: null,
  },
  employee: {
    avatars: [],
    id: '88cea92c-84e5-4c0d-ac21-9998f4b23884',
    firstName: 'Sarah',
    authenticationUid: null,
    avatar: null,
    createdAt: '2020-05-12T11:04:00.864Z',
    createdById: null,
    deletedAt: null,
    disabled: false,
    email: 'sarah@healthcare.com',
    emailVerificationToken: null,
    emailVerificationTokenExpiresAt: null,
    emailVerified: true,
    importHash: null,
    lastName: 'Johnson',
    password: 'employee123',
    passwordResetToken: null,
    passwordResetTokenExpiresAt: null,
    phoneNumber: '+1-555-0102',
    provider: 'local',
    role: 'employee',
    updatedAt: '2020-05-12T11:04:00.864Z',
    updatedById: null,
  }
};

// Default user (for backward compatibility)
export const mockUser = mockUsers.admin;
